#!/bin/bash

# Generated by Merlin

# ── Level 0 (4 resources, parallel) ──
# AzureResourceGroup.rg:merlintest-rg-stg-eas (staging/eastasia)
az group create --name merlintest-rg-stg-eas --location eastasia --tags merlin=true env=staging

# AzureResourceGroup.rg:merlintest-rg-stg-krc (staging/koreacentral)
az group create --name merlintest-rg-stg-krc --location koreacentral --tags merlin=true env=staging

# AzureResourceGroup.rg:merlintest-rg-tst-eas (test/eastasia)
az group create --name merlintest-rg-tst-eas --location eastasia --tags merlin=true env=test

# AzureResourceGroup.rg:merlintest-rg-tst-krc (test/koreacentral)
az group create --name merlintest-rg-tst-krc --location koreacentral --tags merlin=true env=test

# ── Level 1 (10 resources, parallel) ──
# AzureContainerRegistry.alluneed (staging/eastasia)
az acr create --name merlintestalluneedstgeasacr --resource-group merlintest-rg-stg-eas --sku Standard --admin-enabled false --public-network-enabled true --tags merlin=true env=staging
az acr import --name merlintestalluneedstgeasacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed:latest --image alluneed:latest
az acr import --name merlintestalluneedstgeasacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed-basic:latest --image alluneed-basic:latest

# AzureContainerRegistry.alluneed (staging/koreacentral)
az acr create --name merlintestalluneedstgkrcacr --resource-group merlintest-rg-stg-krc --sku Standard --admin-enabled false --public-network-enabled true --tags merlin=true env=staging
az acr import --name merlintestalluneedstgkrcacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed:latest --image alluneed:latest
az acr import --name merlintestalluneedstgkrcacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed-basic:latest --image alluneed-basic:latest

# AzureContainerRegistry.alluneed (test/eastasia)
az acr create --name merlintestalluneedtsteasacr --resource-group merlintest-rg-tst-eas --sku Standard --admin-enabled false --public-network-enabled true --tags merlin=true env=test
az acr import --name merlintestalluneedtsteasacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed:latest --image alluneed:latest
az acr import --name merlintestalluneedtsteasacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed-basic:latest --image alluneed-basic:latest

# AzureContainerRegistry.alluneed (test/koreacentral)
az acr create --name merlintestalluneedtstkrcacr --resource-group merlintest-rg-tst-krc --sku Standard --admin-enabled false --public-network-enabled true --tags merlin=true env=test
az acr import --name merlintestalluneedtstkrcacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed:latest --image alluneed:latest
az acr import --name merlintestalluneedtstkrcacr --source brainlytest-c4cscpe6b9b5f8fq.azurecr.io/alluneed-basic:latest --image alluneed-basic:latest

# AzureLogAnalyticsWorkspace.alluneed (staging/eastasia)
az monitor log-analytics workspace create --name merlintest-alluneed-stg-eas-law --resource-group merlintest-rg-stg-eas --location eastasia --tags merlin=true env=staging

# AzureLogAnalyticsWorkspace.alluneed (staging/koreacentral)
az monitor log-analytics workspace create --name merlintest-alluneed-stg-krc-law --resource-group merlintest-rg-stg-krc --location koreacentral --tags merlin=true env=staging

# AzureLogAnalyticsWorkspace.alluneed (test/eastasia)
az monitor log-analytics workspace create --name merlintest-alluneed-tst-eas-law --resource-group merlintest-rg-tst-eas --location eastasia --tags merlin=true env=test

# AzureLogAnalyticsWorkspace.alluneed (test/koreacentral)
az monitor log-analytics workspace create --name merlintest-alluneed-tst-krc-law --resource-group merlintest-rg-tst-krc --location koreacentral --tags merlin=true env=test

# AzureDnsZone.chuangdns (staging)
az network dns zone update --name chuang.staging.thebrainly.dev --resource-group merlintest-rg-stg --tags environment=staging

# AzureDnsZone.chuangdns (test)
az network dns zone update --name chuang.test.thebrainly.dev --resource-group merlintest-rg-tst --tags environment=test

# ── Level 2 (4 resources, parallel) ──
# AzureContainerAppEnvironment.alluneed (staging/eastasia)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-alluneed-stg-eas-law -g merlintest-rg-stg-eas -o tsv --query customerId)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-alluneed-stg-eas-law -g merlintest-rg-stg-eas -o tsv --query primarySharedKey)
az containerapp env create --name merlintest-alluneed-stg-eas-acenv --resource-group merlintest-rg-stg-eas --logs-workspace-id $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID --logs-workspace-key $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY --tags merlin=true env=staging

# AzureContainerAppEnvironment.alluneed (staging/koreacentral)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-alluneed-stg-krc-law -g merlintest-rg-stg-krc -o tsv --query customerId)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-alluneed-stg-krc-law -g merlintest-rg-stg-krc -o tsv --query primarySharedKey)
az containerapp env create --name merlintest-alluneed-stg-krc-acenv --resource-group merlintest-rg-stg-krc --logs-workspace-id $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID --logs-workspace-key $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY --tags merlin=true env=staging

# AzureContainerAppEnvironment.alluneed (test/eastasia)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-alluneed-tst-eas-law -g merlintest-rg-tst-eas -o tsv --query customerId)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-alluneed-tst-eas-law -g merlintest-rg-tst-eas -o tsv --query primarySharedKey)
az containerapp env create --name merlintest-alluneed-tst-eas-acenv --resource-group merlintest-rg-tst-eas --logs-workspace-id $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID --logs-workspace-key $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY --tags merlin=true env=test

# AzureContainerAppEnvironment.alluneed (test/koreacentral)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-alluneed-tst-krc-law -g merlintest-rg-tst-krc -o tsv --query customerId)
MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-alluneed-tst-krc-law -g merlintest-rg-tst-krc -o tsv --query primarySharedKey)
az containerapp env create --name merlintest-alluneed-tst-krc-acenv --resource-group merlintest-rg-tst-krc --logs-workspace-id $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_CUSTOMERID --logs-workspace-key $MERLIN_AZURELOGANALYTICSWORKSPACE_ALLUNEED_SHAREDKEY --tags merlin=true env=test

# ── Level 3 (4 resources, parallel) ──
# AzureContainerApp.alluneed (staging/eastasia)
MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER=$(az acr show -g merlintest-rg-stg-eas -n merlintestalluneedstgeasacr -o tsv --query loginServer)
MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME=$(echo merlintest-alluneed-stg-eas-acenv)
MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME=$(echo chuang.staging.thebrainly.dev)
az containerapp create --name merlintest-alluneed-stg-eas-aca --resource-group merlintest-rg-stg-eas --image $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER/alluneed:latest --container-name alluneed --cpu 4 --memory 8.0Gi --min-replicas 1 --max-replicas 5 --revisions-mode single --registry-server $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER --registry-identity system --environment $MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=staging MODEL_BLOB_ACCOUNT=chuangdevstorage MODEL_BLOB_CONTAINER=speaker-embedding-models MODEL_BLOB_FOLDER= MODEL_CACHE_FOLDER=.model_cache WAV_CACHE_FOLDER=.wav_cache PROJECT_NAME=alluneed DEBUG_MODE=False LOG_LEVEL=INFO --system-assigned --tags merlin=true env=staging
MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_DNS_ZONE_RG=$(az network dns zone list --query [?name=='$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME'].resourceGroup --output tsv)
MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_ENV_ARM_ID=$(az containerapp show --name merlintest-alluneed-stg-eas-aca --resource-group merlintest-rg-stg-eas --query properties.managedEnvironmentId --output tsv)
MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_ENV_NAME=$(bash -c echo $MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_ENV_ARM_ID | sed 's|.*/||')
MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_FQDN=$(az containerapp show --name merlintest-alluneed-stg-eas-aca --resource-group merlintest-rg-stg-eas --query properties.configuration.ingress.fqdn --output tsv)
az network dns record-set cname set-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name alluneed.eastasia.staging --cname $MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_FQDN
MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_VERIFICATION_ID=$(az containerapp show --name merlintest-alluneed-stg-eas-aca --resource-group merlintest-rg-stg-eas --query properties.customDomainVerificationId --output tsv)
az network dns record-set txt add-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name asuid.alluneed.eastasia.staging --value $MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_VERIFICATION_ID
az containerapp hostname bind --hostname alluneed.eastasia.staging.$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --resource-group merlintest-rg-stg-eas --name merlintest-alluneed-stg-eas-aca --environment $MERLIN_MERLINTEST_ALLUNEED_STG_EAS_ACA_ENV_NAME --validation-method CNAME

# AzureContainerApp.alluneed (staging/koreacentral)
MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER=$(az acr show -g merlintest-rg-stg-krc -n merlintestalluneedstgkrcacr -o tsv --query loginServer)
MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME=$(echo merlintest-alluneed-stg-krc-acenv)
MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME=$(echo chuang.staging.thebrainly.dev)
az containerapp create --name merlintest-alluneed-stg-krc-aca --resource-group merlintest-rg-stg-krc --image $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER/alluneed:latest --container-name alluneed --cpu 4 --memory 8.0Gi --min-replicas 1 --max-replicas 5 --revisions-mode single --registry-server $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER --registry-identity system --environment $MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=staging MODEL_BLOB_ACCOUNT=chuangdevstorage MODEL_BLOB_CONTAINER=speaker-embedding-models MODEL_BLOB_FOLDER= MODEL_CACHE_FOLDER=.model_cache WAV_CACHE_FOLDER=.wav_cache PROJECT_NAME=alluneed DEBUG_MODE=False LOG_LEVEL=INFO --system-assigned --tags merlin=true env=staging
MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_DNS_ZONE_RG=$(az network dns zone list --query [?name=='$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME'].resourceGroup --output tsv)
MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_ENV_ARM_ID=$(az containerapp show --name merlintest-alluneed-stg-krc-aca --resource-group merlintest-rg-stg-krc --query properties.managedEnvironmentId --output tsv)
MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_ENV_NAME=$(bash -c echo $MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_ENV_ARM_ID | sed 's|.*/||')
MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_FQDN=$(az containerapp show --name merlintest-alluneed-stg-krc-aca --resource-group merlintest-rg-stg-krc --query properties.configuration.ingress.fqdn --output tsv)
az network dns record-set cname set-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name alluneed.koreacentral.staging --cname $MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_FQDN
MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_VERIFICATION_ID=$(az containerapp show --name merlintest-alluneed-stg-krc-aca --resource-group merlintest-rg-stg-krc --query properties.customDomainVerificationId --output tsv)
az network dns record-set txt add-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name asuid.alluneed.koreacentral.staging --value $MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_VERIFICATION_ID
az containerapp hostname bind --hostname alluneed.koreacentral.staging.$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --resource-group merlintest-rg-stg-krc --name merlintest-alluneed-stg-krc-aca --environment $MERLIN_MERLINTEST_ALLUNEED_STG_KRC_ACA_ENV_NAME --validation-method CNAME

# AzureContainerApp.alluneed (test/eastasia)
MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER=$(az acr show -g merlintest-rg-tst-eas -n merlintestalluneedtsteasacr -o tsv --query loginServer)
MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME=$(echo merlintest-alluneed-tst-eas-acenv)
MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME=$(echo chuang.test.thebrainly.dev)
az containerapp create --name merlintest-alluneed-tst-eas-aca --resource-group merlintest-rg-tst-eas --image $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER/alluneed:latest --container-name alluneed --cpu 4 --memory 8.0Gi --min-replicas 1 --max-replicas 2 --revisions-mode single --registry-server $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER --registry-identity system --environment $MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=test MODEL_BLOB_ACCOUNT=chuangdevstorage MODEL_BLOB_CONTAINER=speaker-embedding-models MODEL_BLOB_FOLDER= MODEL_CACHE_FOLDER=.model_cache WAV_CACHE_FOLDER=.wav_cache PROJECT_NAME=alluneed DEBUG_MODE=False LOG_LEVEL=INFO --system-assigned --tags merlin=true env=test
MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_DNS_ZONE_RG=$(az network dns zone list --query [?name=='$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME'].resourceGroup --output tsv)
MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_ENV_ARM_ID=$(az containerapp show --name merlintest-alluneed-tst-eas-aca --resource-group merlintest-rg-tst-eas --query properties.managedEnvironmentId --output tsv)
MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_ENV_NAME=$(bash -c echo $MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_ENV_ARM_ID | sed 's|.*/||')
MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_FQDN=$(az containerapp show --name merlintest-alluneed-tst-eas-aca --resource-group merlintest-rg-tst-eas --query properties.configuration.ingress.fqdn --output tsv)
az network dns record-set cname set-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name alluneed.eastasia.test --cname $MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_FQDN
MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_VERIFICATION_ID=$(az containerapp show --name merlintest-alluneed-tst-eas-aca --resource-group merlintest-rg-tst-eas --query properties.customDomainVerificationId --output tsv)
az network dns record-set txt add-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name asuid.alluneed.eastasia.test --value $MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_VERIFICATION_ID
az containerapp hostname bind --hostname alluneed.eastasia.test.$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --resource-group merlintest-rg-tst-eas --name merlintest-alluneed-tst-eas-aca --environment $MERLIN_MERLINTEST_ALLUNEED_TST_EAS_ACA_ENV_NAME --validation-method CNAME

# AzureContainerApp.alluneed (test/koreacentral)
MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER=$(az acr show -g merlintest-rg-tst-krc -n merlintestalluneedtstkrcacr -o tsv --query loginServer)
MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME=$(echo merlintest-alluneed-tst-krc-acenv)
MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME=$(echo chuang.test.thebrainly.dev)
az containerapp create --name merlintest-alluneed-tst-krc-aca --resource-group merlintest-rg-tst-krc --image $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER/alluneed:latest --container-name alluneed --cpu 4 --memory 8.0Gi --min-replicas 1 --max-replicas 2 --revisions-mode single --registry-server $MERLIN_AZURECONTAINERREGISTRY_ALLUNEED_SERVER --registry-identity system --environment $MERLIN_AZURECONTAINERAPPENVIRONMENT_ALLUNEED_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=test MODEL_BLOB_ACCOUNT=chuangdevstorage MODEL_BLOB_CONTAINER=speaker-embedding-models MODEL_BLOB_FOLDER= MODEL_CACHE_FOLDER=.model_cache WAV_CACHE_FOLDER=.wav_cache PROJECT_NAME=alluneed DEBUG_MODE=False LOG_LEVEL=INFO --system-assigned --tags merlin=true env=test
MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_DNS_ZONE_RG=$(az network dns zone list --query [?name=='$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME'].resourceGroup --output tsv)
MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_ENV_ARM_ID=$(az containerapp show --name merlintest-alluneed-tst-krc-aca --resource-group merlintest-rg-tst-krc --query properties.managedEnvironmentId --output tsv)
MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_ENV_NAME=$(bash -c echo $MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_ENV_ARM_ID | sed 's|.*/||')
MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_FQDN=$(az containerapp show --name merlintest-alluneed-tst-krc-aca --resource-group merlintest-rg-tst-krc --query properties.configuration.ingress.fqdn --output tsv)
az network dns record-set cname set-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name alluneed.koreacentral.test --cname $MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_FQDN
MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_VERIFICATION_ID=$(az containerapp show --name merlintest-alluneed-tst-krc-aca --resource-group merlintest-rg-tst-krc --query properties.customDomainVerificationId --output tsv)
az network dns record-set txt add-record --resource-group $MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_DNS_ZONE_RG --zone-name $MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --record-set-name asuid.alluneed.koreacentral.test --value $MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_VERIFICATION_ID
az containerapp hostname bind --hostname alluneed.koreacentral.test.$MERLIN_AZUREDNSZONE_CHUANGDNS_DOMAINNAME --resource-group merlintest-rg-tst-krc --name merlintest-alluneed-tst-krc-aca --environment $MERLIN_MERLINTEST_ALLUNEED_TST_KRC_ACA_ENV_NAME --validation-method CNAME
