#!/bin/bash

# Generated by Merlin

# chuangacr (staging/eastasia)
az group create --name merlintest-rg-stg-eas --location eastasia --tags merlin=true env=staging
az acr create --name merlintestchuangacrstgeasacr --resource-group merlintest-rg-stg-eas --sku Standard --admin-enabled false --allow-exports true --allow-trusted-services true --public-network-enabled true --tags merlin=true env=staging
az acr login --name merlintestchuangacrstgeasacr
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrstgeasacr.azurecr.io/chuangdemo:latest
docker push merlintestchuangacrstgeasacr.azurecr.io/chuangdemo:latest
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrstgeasacr.azurecr.io/chuangdemo:v0.0.1
docker push merlintestchuangacrstgeasacr.azurecr.io/chuangdemo:v0.0.1

# chuangacr (staging/koreacentral)
az group create --name merlintest-rg-stg-krc --location koreacentral --tags merlin=true env=staging
az acr create --name merlintestchuangacrstgkrcacr --resource-group merlintest-rg-stg-krc --sku Standard --admin-enabled false --allow-exports true --allow-trusted-services true --public-network-enabled true --tags merlin=true env=staging
az acr login --name merlintestchuangacrstgkrcacr
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrstgkrcacr.azurecr.io/chuangdemo:latest
docker push merlintestchuangacrstgkrcacr.azurecr.io/chuangdemo:latest
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrstgkrcacr.azurecr.io/chuangdemo:v0.0.1
docker push merlintestchuangacrstgkrcacr.azurecr.io/chuangdemo:v0.0.1

# chuangacr (test/eastasia)
az group create --name merlintest-rg-tst-eas --location eastasia --tags merlin=true env=test
az acr create --name merlintestchuangacrtsteasacr --resource-group merlintest-rg-tst-eas --sku Basic --admin-enabled false --allow-exports true --allow-trusted-services true --public-network-enabled true --tags merlin=true env=test
az acr login --name merlintestchuangacrtsteasacr
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrtsteasacr.azurecr.io/chuangdemo:latest
docker push merlintestchuangacrtsteasacr.azurecr.io/chuangdemo:latest
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrtsteasacr.azurecr.io/chuangdemo:v0.0.1
docker push merlintestchuangacrtsteasacr.azurecr.io/chuangdemo:v0.0.1

# chuangacr (test/koreacentral)
az group create --name merlintest-rg-tst-krc --location koreacentral --tags merlin=true env=test
az acr create --name merlintestchuangacrtstkrcacr --resource-group merlintest-rg-tst-krc --sku Basic --admin-enabled false --allow-exports true --allow-trusted-services true --public-network-enabled true --tags merlin=true env=test
az acr login --name merlintestchuangacrtstkrcacr
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrtstkrcacr.azurecr.io/chuangdemo:latest
docker push merlintestchuangacrtstkrcacr.azurecr.io/chuangdemo:latest
docker pull mcr.microsoft.com/mcr/hello-world
docker tag mcr.microsoft.com/mcr/hello-world merlintestchuangacrtstkrcacr.azurecr.io/chuangdemo:v0.0.1
docker push merlintestchuangacrtstkrcacr.azurecr.io/chuangdemo:v0.0.1

# chuanglaw (staging/eastasia)
az group create --name merlintest-rg-stg-eas --location eastasia --tags merlin=true env=staging
az monitor log-analytics workspace create --name merlintest-chuanglaw-stg-eas-law --resource-group merlintest-rg-stg-eas --location eastasia --tags merlin=true env=staging

# chuanglaw (staging/koreacentral)
az group create --name merlintest-rg-stg-krc --location koreacentral --tags merlin=true env=staging
az monitor log-analytics workspace create --name merlintest-chuanglaw-stg-krc-law --resource-group merlintest-rg-stg-krc --location koreacentral --tags merlin=true env=staging

# chuanglaw (test/eastasia)
az group create --name merlintest-rg-tst-eas --location eastasia --tags merlin=true env=test
az monitor log-analytics workspace create --name merlintest-chuanglaw-tst-eas-law --resource-group merlintest-rg-tst-eas --location eastasia --tags merlin=true env=test

# chuanglaw (test/koreacentral)
az group create --name merlintest-rg-tst-krc --location koreacentral --tags merlin=true env=test
az monitor log-analytics workspace create --name merlintest-chuanglaw-tst-krc-law --resource-group merlintest-rg-tst-krc --location koreacentral --tags merlin=true env=test

# chuangacenv (staging/eastasia)
MERLIN_CHUANGLAW_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-chuanglaw-stg-eas-law -g merlintest-rg-stg-eas -o tsv --query customerId)
MERLIN_CHUANGLAW_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-chuanglaw-stg-eas-law -g merlintest-rg-stg-eas -o tsv --query primarySharedKey)
az group create --name merlintest-rg-stg-eas --location eastasia --tags merlin=true env=staging
az containerapp env create --name merlintest-chuangacenv-stg-eas-acenv --resource-group merlintest-rg-stg-eas --logs-workspace-id $MERLIN_CHUANGLAW_CUSTOMERID --logs-workspace-key $MERLIN_CHUANGLAW_SHAREDKEY --tags merlin=true env=staging

# chuangacenv (staging/koreacentral)
MERLIN_CHUANGLAW_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-chuanglaw-stg-krc-law -g merlintest-rg-stg-krc -o tsv --query customerId)
MERLIN_CHUANGLAW_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-chuanglaw-stg-krc-law -g merlintest-rg-stg-krc -o tsv --query primarySharedKey)
az group create --name merlintest-rg-stg-krc --location koreacentral --tags merlin=true env=staging
az containerapp env create --name merlintest-chuangacenv-stg-krc-acenv --resource-group merlintest-rg-stg-krc --logs-workspace-id $MERLIN_CHUANGLAW_CUSTOMERID --logs-workspace-key $MERLIN_CHUANGLAW_SHAREDKEY --tags merlin=true env=staging

# chuangacenv (test/eastasia)
MERLIN_CHUANGLAW_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-chuanglaw-tst-eas-law -g merlintest-rg-tst-eas -o tsv --query customerId)
MERLIN_CHUANGLAW_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-chuanglaw-tst-eas-law -g merlintest-rg-tst-eas -o tsv --query primarySharedKey)
az group create --name merlintest-rg-tst-eas --location eastasia --tags merlin=true env=test
az containerapp env create --name merlintest-chuangacenv-tst-eas-acenv --resource-group merlintest-rg-tst-eas --logs-workspace-id $MERLIN_CHUANGLAW_CUSTOMERID --logs-workspace-key $MERLIN_CHUANGLAW_SHAREDKEY --tags merlin=true env=test

# chuangacenv (test/koreacentral)
MERLIN_CHUANGLAW_CUSTOMERID=$(az monitor log-analytics workspace show --name merlintest-chuanglaw-tst-krc-law -g merlintest-rg-tst-krc -o tsv --query customerId)
MERLIN_CHUANGLAW_SHAREDKEY=$(az monitor log-analytics workspace get-shared-keys --name merlintest-chuanglaw-tst-krc-law -g merlintest-rg-tst-krc -o tsv --query primarySharedKey)
az group create --name merlintest-rg-tst-krc --location koreacentral --tags merlin=true env=test
az containerapp env create --name merlintest-chuangacenv-tst-krc-acenv --resource-group merlintest-rg-tst-krc --logs-workspace-id $MERLIN_CHUANGLAW_CUSTOMERID --logs-workspace-key $MERLIN_CHUANGLAW_SHAREDKEY --tags merlin=true env=test

# chuangaca (staging/eastasia)
MERLIN_CHUANGACR_SERVER=$(az acr show -g merlintest-rg-stg-eas -n merlintestchuangacrstgeasacr -o tsv --query loginServer)
MERLIN_CHUANGACENV_NAME=$(echo merlintest-chuangacenv-stg-eas-acenv)
az group create --name merlintest-rg-stg-eas --location eastasia --tags merlin=true env=staging
az containerapp create --name merlintest-chuangaca-stg-eas-aca --resource-group merlintest-rg-stg-eas --image $MERLIN_CHUANGACR_SERVER/chuangdemo:latest --container-name chuangdemo --cpu 1 --memory 2.0Gi --min-replicas 1 --max-replicas 5 --revisions-mode single --registry-server $MERLIN_CHUANGACR_SERVER --registry-identity system --environment $MERLIN_CHUANGACENV_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=staging --system-assigned --tags merlin=true env=staging

# chuangaca (staging/koreacentral)
MERLIN_CHUANGACR_SERVER=$(az acr show -g merlintest-rg-stg-krc -n merlintestchuangacrstgkrcacr -o tsv --query loginServer)
MERLIN_CHUANGACENV_NAME=$(echo merlintest-chuangacenv-stg-krc-acenv)
az group create --name merlintest-rg-stg-krc --location koreacentral --tags merlin=true env=staging
az containerapp create --name merlintest-chuangaca-stg-krc-aca --resource-group merlintest-rg-stg-krc --image $MERLIN_CHUANGACR_SERVER/chuangdemo:latest --container-name chuangdemo --cpu 1 --memory 2.0Gi --min-replicas 1 --max-replicas 5 --revisions-mode single --registry-server $MERLIN_CHUANGACR_SERVER --registry-identity system --environment $MERLIN_CHUANGACENV_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=staging --system-assigned --tags merlin=true env=staging

# chuangaca (test/eastasia)
MERLIN_CHUANGACR_SERVER=$(az acr show -g merlintest-rg-tst-eas -n merlintestchuangacrtsteasacr -o tsv --query loginServer)
MERLIN_CHUANGACENV_NAME=$(echo merlintest-chuangacenv-tst-eas-acenv)
az group create --name merlintest-rg-tst-eas --location eastasia --tags merlin=true env=test
az containerapp create --name merlintest-chuangaca-tst-eas-aca --resource-group merlintest-rg-tst-eas --image $MERLIN_CHUANGACR_SERVER/chuangdemo:latest --container-name chuangdemo --cpu 0.25 --memory 0.5Gi --min-replicas 0 --max-replicas 1 --revisions-mode single --registry-server $MERLIN_CHUANGACR_SERVER --registry-identity system --environment $MERLIN_CHUANGACENV_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=test --system-assigned --tags merlin=true env=test

# chuangaca (test/koreacentral)
MERLIN_CHUANGACR_SERVER=$(az acr show -g merlintest-rg-tst-krc -n merlintestchuangacrtstkrcacr -o tsv --query loginServer)
MERLIN_CHUANGACENV_NAME=$(echo merlintest-chuangacenv-tst-krc-acenv)
az group create --name merlintest-rg-tst-krc --location koreacentral --tags merlin=true env=test
az containerapp create --name merlintest-chuangaca-tst-krc-aca --resource-group merlintest-rg-tst-krc --image $MERLIN_CHUANGACR_SERVER/chuangdemo:latest --container-name chuangdemo --cpu 0.25 --memory 0.5Gi --min-replicas 0 --max-replicas 1 --revisions-mode single --registry-server $MERLIN_CHUANGACR_SERVER --registry-identity system --environment $MERLIN_CHUANGACENV_NAME --ingress external --target-port 8080 --transport auto --allow-insecure false --env-vars APP_ENV=test --system-assigned --tags merlin=true env=test
