name: trinity-home
type: KubernetesIngress
project: merlin
ring:
  - test
  - staging
region:
  - koreacentral
  - eastasia

dependencies:
  - resource: KubernetesService.trinity-home
    isHardDependency: true

defaultConfig:
  namespace: trinity
  ingressClassName: nginx
  clusterIssuer: letsencrypt-prod

  rules:
    - host: home.test.thebrainly.dev
      paths:
        - path: /
          pathType: Prefix
          serviceName: trinity-home
          servicePort: 3000

  tls:
    - hosts:
        - home.test.thebrainly.dev
      secretName: trinity-home-tls

specificConfig:
  - ring: staging
    rules:
      - host: home.staging.thebrainly.dev
        paths:
          - path: /
            pathType: Prefix
            serviceName: trinity-home
            servicePort: 3000
    tls:
      - hosts:
          - home.staging.thebrainly.dev
        secretName: trinity-home-tls

exports: {}
