/**
 * Generates the deploy.ts script content with the correct package name injected.
 * Replaces the static deploy-script.ts.template file.
 */

import { MERLIN_PACKAGE_NAME } from '../common/constants.js';

export function generateDeployScript(): string {
    return `/**
 * Auto-generated deploy script
 * DO NOT EDIT - This file is generated by Merlin Compiler
 */
import {
  getAllResources
} from './index.js';

import '${MERLIN_PACKAGE_NAME}/init.js';
import './index.js'; // Import all resources to register them
import { deployer } from '${MERLIN_PACKAGE_NAME}/deployer.js';

interface CliOptions {
  ring?: string;
  region?: string;
  execute: boolean;
  outputFile?: string;
  concurrency?: number;
  noShared?: boolean;
}

/**
 * Parse command line arguments
 */
function parseArguments(): CliOptions {
  const args = process.argv.slice(2);
  const options: CliOptions = {
    execute: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg === '--execute' || arg === '-e') {
      options.execute = true;
    } else if (arg === '--ring' || arg === '-r') {
      options.ring = args[++i];
    } else if (arg === '--region') {
      options.region = args[++i];
    } else if (arg === '--output' || arg === '-o') {
      options.outputFile = args[++i];
    } else if (arg === '--concurrency' || arg === '-c') {
      const val = parseInt(args[++i], 10);
      if (!isNaN(val) && val > 0) {
        options.concurrency = val;
      }
    } else if (arg === '--no-shared') {
      options.noShared = true;
    } else if (arg === '--help' || arg === '-h') {
      console.log(\`
Usage: node deploy.js [options]

Options:
  --execute, -e              Execute the deployment (default is dry-run)
  --ring, -r <ring>          Target ring (test, staging, production)
  --region <region>          Target region (eastus, westus, eastasia, koreacentral, koreasouth)
  --output, -o <file>        Write generated commands to file
  --concurrency, -c <n>      Max parallel resource deployments per level (default: 4)
  --no-shared                Skip deploying shared resources (still registered for resolution)
  --help, -h                 Show this help message

Examples:
  node deploy.js                                  # Show all deployment commands
  node deploy.js --ring staging                   # Show commands for staging ring
  node deploy.js --execute --ring test            # Execute deployment for test ring
  node deploy.js --execute --concurrency 2        # Execute with max 2 parallel deployments
  node deploy.js -o deploy.sh                     # Write commands to deploy.sh file
  node deploy.js --ring production -o prod.sh     # Write production commands to file
\`);
      process.exit(0);
    }
  }

  return options;
}

/**
 * Main function
 */
async function main() {
  const options = parseArguments();

  try {
    await deployer.deploy(options);
  } catch (error) {
    console.error('Deployment failed:', error);
    process.exit(1);
  }
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
`;
}
