/**
 * TypeScript code generator for resources
 */

import * as path from 'path';
import { ExpandedResource, GeneratedFile } from './types.js';

/**
 * Generates TypeScript code from expanded resources
 */
export function generate(sourcePath: string, resources: ExpandedResource[]): GeneratedFile {
    const fileName = path.basename(sourcePath, '.yml') + '.ts';
    const resourceNames: string[] = [];

    // Generate imports
    let code = generateImports(sourcePath);
    code += '\n\n';

    // Add source comment
    code += `// Source: ${sourcePath}\n\n`;

    // Generate each resource
    for (const resource of resources) {
        const resourceName = generateResourceName(resource);
        resourceNames.push(resourceName);

        code += `export const ${resourceName}: Resource = ${generateResourceObject(resource)};\n\n`;

        // Auto-register
        code += `registerResource(${resourceName});\n\n`;
    }

    return {
        fileName,
        content: code,
        resources: resourceNames
    };
}

/**
 * Generates the index.ts barrel export file
 */
export function generateIndex(files: GeneratedFile[]): GeneratedFile {
    let code = '// Auto-generated barrel export\n';
    code += '// DO NOT EDIT - This file is generated by Merlin Compiler\n\n';

    for (const file of files) {
        const moduleName = path.basename(file.fileName, '.ts');
        code += `export * from './${moduleName}.js';\n`;
    }

    // Re-export getAllResources from runtime for deploy script
    code += '\n// Re-export runtime utilities for deployment\n';
    code += `export { getAllResources } from 'merlin/runtime.js';\n`;

    return {
        fileName: 'index.ts',
        content: code,
        resources: []
    };
}

/**
 * Generates the import statements
 */
function generateImports(sourcePath: string): string {
    return `// Auto-generated by Merlin Compiler
// DO NOT EDIT - This file is generated from YAML resource definitions

import 'merlin/init.js'; // Initialize providers before importing runtime
import { Resource, getAuthProvider, getProprietyGetter, registerResource } from 'merlin/runtime.js';`;
}

/**
 * Generates the resource variable name
 */
function generateResourceName(resource: ExpandedResource): string {
    // With region: type_name_ring_region
    // Without region: type_name_ring
    const parts = [resource.type, resource.name, resource.ring];
    if (resource.region) {
        parts.push(resource.region);
    }
    return parts.join('_');
}

/**
 * Generates the Resource object literal
 */
function generateResourceObject(resource: ExpandedResource): string {
    let code = '{\n';

    // Basic fields
    code += `  name: ${JSON.stringify(resource.name)},\n`;
    code += `  ring: ${JSON.stringify(resource.ring)},\n`;

    if (resource.region) {
        code += `  region: ${JSON.stringify(resource.region)},\n`;
    }

    code += `  type: ${JSON.stringify(resource.type)},\n`;

    if (resource.project) {
        code += `  project: ${JSON.stringify(resource.project)},\n`;
    }

    if (resource.parent) {
        code += `  parent: ${JSON.stringify(resource.parent)},\n`;
    }

    // AuthProvider - now includes args (optional)
    if (resource.authProvider) {
        code += `  authProvider: {\n`;
        code += `    provider: getAuthProvider(${JSON.stringify(resource.authProvider.name)}),\n`;
        code += `    args: ${JSON.stringify(resource.authProvider.args)}\n`;
        code += `  },\n`;
    }

    // Dependencies
    code += `  dependencies: ${JSON.stringify(resource.dependencies, null, 2)},\n`;

    // Config (merged from defaultConfig + specificConfig during compilation)
    code += `  config: ${formatJSON(resource.config, 2)},\n`;

    // Exports - resolve getters by name
    code += `  exports: {\n`;
    for (const [key, value] of Object.entries(resource.exports)) {
        code += `    ${JSON.stringify(key)}: {\n`;
        code += `      getter: getProprietyGetter(${JSON.stringify(value.name)}),\n`;
        code += `      args: ${JSON.stringify(value.args)}\n`;
        code += `    },\n`;
    }
    code += `  }\n`;

    code += '}';

    return code;
}

/**
 * Formats JSON with proper indentation
 */
function formatJSON(obj: unknown, indent: number): string {
    const lines = JSON.stringify(obj, null, 2).split('\n');
    if (lines.length === 1) {
        return lines[0];
    }

    // Add indentation to all lines except the first
    return lines
        .map((line, index) => {
            if (index === 0) return line;
            return ' '.repeat(indent) + line;
        })
        .join('\n');
}
