/**
 * TypeScript code generator for resources
 */

import * as path from 'path';
import { ExpandedResource, GeneratedFile } from './types.js';
import { MERLIN_PACKAGE_NAME } from '../common/constants.js';

/**
 * Generates TypeScript code from expanded resources
 */
export function generate(sourcePath: string, resources: ExpandedResource[]): GeneratedFile {
    const fileName = path.basename(sourcePath, '.yml') + '.ts';
    const resourceNames: string[] = [];

    // Generate imports
    let code = generateImports(sourcePath);
    code += '\n\n';

    // Add source comment
    code += `// Source: ${sourcePath}\n\n`;

    // Generate each resource
    for (const resource of resources) {
        const resourceName = generateResourceName(resource);
        resourceNames.push(resourceName);

        code += `export const ${resourceName}: Resource = ${generateResourceObject(resource)};\n\n`;

        // Auto-register
        code += `registerResource(${resourceName});\n\n`;
    }

    return {
        fileName,
        content: code,
        resources: resourceNames
    };
}

/**
 * Generates the index.ts barrel export file
 */
export function generateIndex(files: GeneratedFile[]): GeneratedFile {
    let code = '// Auto-generated barrel export\n';
    code += '// DO NOT EDIT - This file is generated by Merlin Compiler\n\n';

    for (const file of files) {
        const moduleName = path.basename(file.fileName, '.ts');
        code += `export * from './${moduleName}.js';\n`;
    }

    // Re-export getAllResources from runtime for deploy script
    code += '\n// Re-export runtime utilities for deployment\n';
    code += `export { getAllResources } from '${MERLIN_PACKAGE_NAME}/runtime.js';\n`;

    return {
        fileName: 'index.ts',
        content: code,
        resources: []
    };
}

/**
 * Generates the import statements
 */
function generateImports(sourcePath: string): string {
    return `// Auto-generated by Merlin Compiler
// DO NOT EDIT - This file is generated from YAML resource definitions

import '${MERLIN_PACKAGE_NAME}/init.js'; // Initialize providers before importing runtime
import { Resource, getAuthProvider, getPropertyGetter, registerResource } from '${MERLIN_PACKAGE_NAME}/runtime.js';`;
}

/**
 * Generates the resource variable name
 */
function generateResourceName(resource: ExpandedResource): string {
    // With ring+region: type_name_ring_region
    // With ring only: type_name_ring
    // No ring, with region: type_name_region
    // No ring, no region: type_name
    const parts = [resource.type, resource.name];
    if (resource.ring) {
        parts.push(resource.ring);
    }
    if (resource.region) {
        parts.push(resource.region);
    }
    return parts.join('_').replace(/[^a-zA-Z0-9_]/g, '_');
}

/**
 * Generates the Resource object literal
 */
function generateResourceObject(resource: ExpandedResource): string {
    let code = '{\n';

    // Basic fields
    code += `  name: ${JSON.stringify(resource.name)},\n`;

    if (resource.ring) {
        code += `  ring: ${JSON.stringify(resource.ring)},\n`;
    }

    if (resource.region) {
        code += `  region: ${JSON.stringify(resource.region)},\n`;
    }

    code += `  type: ${JSON.stringify(resource.type)},\n`;

    if (resource.project) {
        code += `  project: ${JSON.stringify(resource.project)},\n`;
    }

    if (resource.parent) {
        code += `  parent: ${JSON.stringify(resource.parent)},\n`;
    }

    // AuthProvider - now includes args (optional)
    if (resource.authProvider) {
        code += `  authProvider: {\n`;
        code += `    provider: getAuthProvider(${JSON.stringify(resource.authProvider.name)}),\n`;
        code += `    args: ${JSON.stringify(resource.authProvider.args)}\n`;
        code += `  },\n`;
    }

    // Dependencies — dep.authProvider must be resolved via getAuthProvider() at runtime,
    // not serialized as a plain JSON object (which would lack the .apply() method).
    code += `  dependencies: [\n`;
    for (const dep of resource.dependencies) {
        code += `  {\n`;
        code += `    resource: ${JSON.stringify(dep.resource)},\n`;
        if (dep.isHardDependency !== undefined) {
            code += `    isHardDependency: ${dep.isHardDependency},\n`;
        }
        if (dep.authProvider) {
            const { name: apName, ...apArgs } = dep.authProvider;
            code += `    authProvider: {\n`;
            code += `      provider: getAuthProvider(${JSON.stringify(apName)}),\n`;
            code += `      args: ${JSON.stringify(apArgs)}\n`;
            code += `    },\n`;
        }
        code += `  },\n`;
    }
    code += `  ],\n`;

    // Config (merged from defaultConfig + specificConfig during compilation)
    code += `  config: ${formatJSON(resource.config, 2)},\n`;

    // Exports - resolve getters by name
    code += `  exports: {\n`;
    for (const [key, value] of Object.entries(resource.exports)) {
        code += `    ${JSON.stringify(key)}: {\n`;
        code += `      getter: getPropertyGetter(${JSON.stringify(value.name)}),\n`;
        code += `      args: ${JSON.stringify(value.args)}\n`;
        code += `    },\n`;
    }
    code += `  }\n`;

    code += '}';

    return code;
}

/**
 * Formats JSON with proper indentation
 */
function formatJSON(obj: unknown, indent: number): string {
    const lines = JSON.stringify(obj, null, 2).split('\n');
    if (lines.length === 1) {
        return lines[0];
    }

    // Add indentation to all lines except the first
    return lines
        .map((line, index) => {
            if (index === 0) return line;
            return ' '.repeat(indent) + line;
        })
        .join('\n');
}
