/**
 * Deployment orchestration module
 * Handles resource deployment using render functions from the registry
 */

import { Resource, Command } from './common/resource.js';
import { getAllResources } from './common/registry.js';
import { getRender } from './common/resource.js';
import { execa } from 'execa';
import * as fs from 'fs/promises';

export interface DeployOptions {
  ring?: string;
  region?: string;
  execute: boolean;
  outputFile?: string;
}

export class Deployer {
  /**
   * Main deployment orchestration function
   */
  async deploy(options: DeployOptions): Promise<void> {
    // 1. Get all resources and filter by ring/region
    const resources = this.filterResources(getAllResources(), options);

    if (resources.length === 0) {
      console.log('No resources match the specified filters');
      return;
    }

    // 2. Render commands for each resource
    const allCommands: Array<{ resource: Resource; commands: Command[] }> = [];

    for (const resource of resources) {
      console.log(`Rendering ${resource.name} (${resource.ring}${resource.region ? `/${resource.region}` : ''})...`);

      try {
        const render = getRender(resource.type);
        const commands = await render.render(resource);
        allCommands.push({ resource, commands });
      } catch (error) {
        console.error(`Failed to render ${resource.name}:`, error);
        throw error;
      }
    }

    // 3. Output or execute commands based on options
    if (options.outputFile) {
      await this.writeCommandsToFile(allCommands, options.outputFile);
    }

    if (options.execute) {
      await this.executeCommands(allCommands);
    } else if (!options.outputFile) {
      // Only print if not already writing to file
      this.printCommands(allCommands);
    }
  }

  /**
   * Filter resources by ring and region
   */
  private filterResources(resources: Resource[], options: DeployOptions): Resource[] {
    return resources.filter(resource => {
      if (options.ring && resource.ring !== options.ring) {
        return false;
      }
      if (options.region && resource.region !== options.region) {
        return false;
      }
      return true;
    });
  }

  /**
   * Execute commands sequentially with error handling
   */
  private async executeCommands(
    allCommands: Array<{ resource: Resource; commands: Command[] }>
  ): Promise<void> {
    console.log('\nExecuting deployment commands...\n');

    for (const { resource, commands } of allCommands) {
      console.log(`Deploying ${resource.name} (${resource.ring}${resource.region ? `/${resource.region}` : ''})...`);

      for (const command of commands) {
        const commandStr = `${command.command} ${command.args.join(' ')}`;
        console.log(`> ${commandStr}`);

        try {
          const { stdout, stderr } = await execa(command.command, command.args);

          if (stdout) {
            console.log(stdout);
          }
          if (stderr) {
            console.error(stderr);
          }

          // Parse result if parser is provided
          if (command.resultParser && stdout) {
            const parsed = command.resultParser(stdout);
            // Store or use parsed result if needed in the future
          }
        } catch (error) {
          console.error(`✗ Failed to execute: ${commandStr}`);
          console.error(error);
          throw error;
        }
      }

      console.log('');
    }

    console.log('Deployment completed successfully!');
  }

  /**
   * Print commands without executing
   */
  private printCommands(allCommands: Array<{ resource: Resource; commands: Command[] }>): void {
    console.log('\nGenerated deployment commands (dry-run mode):\n');

    for (const { resource, commands } of allCommands) {
      console.log(`# ${resource.name} (${resource.ring}${resource.region ? `/${resource.region}` : ''})`);
      for (const command of commands) {
        console.log(`${command.command} ${command.args.join(' ')}`);
      }
      console.log('');
    }

    console.log('Use --execute flag to actually run these commands');
    console.log('Use --output <file> to write commands to a file');
  }

  /**
   * Write commands to shell script file
   */
  private async writeCommandsToFile(
    allCommands: Array<{ resource: Resource; commands: Command[] }>,
    outputFile: string
  ): Promise<void> {
    const lines = ['#!/bin/bash', '', '# Generated by Merlin', ''];

    for (const { resource, commands } of allCommands) {
      lines.push(`# ${resource.name} (${resource.ring}${resource.region ? `/${resource.region}` : ''})`);
      for (const command of commands) {
        lines.push(`${command.command} ${command.args.join(' ')}`);
      }
      lines.push('');
    }

    await fs.writeFile(outputFile, lines.join('\n'), { mode: 0o755 });
    console.log(`✅ Deployment commands written to: ${outputFile}`);
    console.log(`   Total commands: ${allCommands.reduce((sum, { commands }) => sum + commands.length, 0)}`);
  }
}

// Export singleton instance
export const deployer = new Deployer();
