/**
 * Runtime exports for generated code
 * This module provides the public API for code generated by the Merlin compiler
 */

// Re-export types needed by generated code
export type {
    Resource,
    ResourceSchema,
    Ring,
    Region,
    Dependency,
    AuthProvider,
    ProprietyGetter,
    Command,
    Render
} from './common/resource.js';

// Re-export functions used by generated code
export {
    getAuthProvider,
    getProprietyGetter,
    getRender,
    registerAuthProvider,
    registerProprietyGetter,
    registerRender,
    commandToString,
} from './common/resource.js';

export {
    registerResource,
    getResource,
    getAllResources,
    clearRegistry
} from './common/registry.js';

// Export deployer for deployment orchestration
export {
    deployer,
    Deployer
} from './deployer.js';

export type {
    DeployOptions
} from './deployer.js';
